---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.2
  - name: centos-6.7
  - name: centos-5.11
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        config: &default-config
          bootstrap: true
          server: true
          datacenter: FortMeade
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
    excludes:
      - windows-2012r2
  - name: source
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        config: *default-config
        service:
          install_method: source
    excludes:
      - windows-2012r2
  - name: package
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        config: *default-config
        service:
          install_method: package
    excludes:
      - centos-7.2
      - centos-6.7
      - centos-5.11
  - name: acl
    run_list:
      - recipe[consul::default]
      - recipe[consul::client_gem]
      - recipe[consul_spec::acl]
    attributes:
      consul:
        config:
          bootstrap: true
          server: true
          datacenter: fortmeade
          acl_master_token: doublesecret
          acl_datacenter: fortmeade
          acl_default_policy: deny
    excludes:
      - windows-2012r2
      - centos-7.2
      - centos-6.7
      - centos-5.11
  - name: windefault
    includes:
      - windows-2012r2
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        service_user: vagrant
        config: *default-config
        service:
          nssm_params:
            AppStdout: C:\foo\bar\out.log
            AppStderr: C:\foo\bar\err.log
